-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 17:05:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS quizmaster;
CREATE SCHEMA IF NOT EXISTS `quizmaster` DEFAULT CHARACTER SET utf8 ;
USE `quizmaster` ;

-- -----------------------------------------------------
-- Table `quizmaster`.`Gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Gebruiker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `inlognaam` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsels` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `inlognaam_UNIQUE` (`inlognaam` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Cursus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Cursus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `coordinatorid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cursus_Gebruiker1_idx` (`coordinatorid` ASC) VISIBLE,
  CONSTRAINT `fk_Cursus_Gebruiker1`
    FOREIGN KEY (`coordinatorid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE RESTRICT
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `succesdefinitie` INT NOT NULL,
  `cursusid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Quiz_Cursus1_idx` (`cursusid` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_Cursus1`
    FOREIGN KEY (`cursusid`)
    REFERENCES `quizmaster`.`Cursus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Vraag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Vraag` (
  `id` INT NOT NULL,
  `tekst` VARCHAR(150) NOT NULL,
  `quizid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vraag_Quiz1_idx` (`quizid` ASC) VISIBLE,
  CONSTRAINT `fk_Vraag_Quiz1`
    FOREIGN KEY (`quizid`)
    REFERENCES `quizmaster`.`Quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Antwoord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Antwoord` (
  `id` INT NOT NULL,
  `tekst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Vraagantwoord_optie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Vraagantwoord_optie` (
  `vraagid` INT NOT NULL,
  `antwoordid` INT NOT NULL,
  `isjuistantwoord` TINYINT NOT NULL,
  INDEX `fk_Vraag_has_Antwoord_Antwoord1_idx` (`antwoordid` ASC) VISIBLE,
  PRIMARY KEY (`vraagid`, `antwoordid`),
  CONSTRAINT `fk_Vraag_has_Antwoord_Vraag1`
    FOREIGN KEY (`vraagid`)
    REFERENCES `quizmaster`.`Vraag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Vraag_has_Antwoord_Antwoord1`
    FOREIGN KEY (`antwoordid`)
    REFERENCES `quizmaster`.`Antwoord` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Groep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Groep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `docentid` INT NULL,
  `cursusid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Groep_Cursus1_idx` (`cursusid` ASC) VISIBLE,
  INDEX `fk_Groep_Gebruiker1_idx` (`docentid` ASC) VISIBLE,
  CONSTRAINT `fk_Groep_Cursus1`
    FOREIGN KEY (`cursusid`)
    REFERENCES `quizmaster`.`Cursus` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Groep_Gebruiker1`
    FOREIGN KEY (`docentid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Groepsindeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Groepsindeling` (
  `gebruikerid` INT NOT NULL,
  `groepid` INT NOT NULL,
  INDEX `fk_Gebruiker_has_Groep_Groep1_idx` (`groepid` ASC) VISIBLE,
  PRIMARY KEY (`gebruikerid`, `groepid`),
  CONSTRAINT `fk_Gebruiker_has_Groep_Gebruiker1`
    FOREIGN KEY (`gebruikerid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gebruiker_has_Groep_Groep1`
    FOREIGN KEY (`groepid`)
    REFERENCES `quizmaster`.`Groep` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Quizresultaat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Quizresultaat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `studentid` INT NOT NULL,
  `quizid` INT NULL,
  `quiznaam` VARCHAR(45) NOT NULL,
  `succesdefinitie` INT NOT NULL,
  `aantaljuisteantwoorden` INT NOT NULL,
  `voltooidop` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gebruiker_has_Quiz_Quiz1_idx` (`quizid` ASC) VISIBLE,
  INDEX `fk_Gebruiker_has_Quiz_Gebruiker1_idx` (`studentid` ASC) VISIBLE,
  CONSTRAINT `fk_Gebruiker_has_Quiz_Gebruiker1`
    FOREIGN KEY (`studentid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gebruiker_has_Quiz_Quiz1`
    FOREIGN KEY (`quizid`)
    REFERENCES `quizmaster`.`Quiz` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Gebruiker definiëren en toegang verlenen
CREATE USER IF NOT EXISTS userQuizmaster@localhost IDENTIFIED BY 'pwQuizmaster';
GRANT ALL PRIVILEGES ON quizmaster . * TO userQuizmaster@localhost;

-- INSERT

INSERT INTO gebruiker
VALUES(DEFAULT, 'Student','Hans', '12345', 'Hans', null, 'Janssen'), 
(DEFAULT, 'Coordinator','Piet', '12345', 'Piet', null, 'Janssen'),
(DEFAULT, 'Docent','Anna', '12345', 'Anna', null, 'Janssen'),
(DEFAULT, 'Administrator','Mickey', '12345', 'Mickey', null, 'Janssen'),
(DEFAULT, 'Technisch beheerder','Dorien', '12345', 'Dorien', null, 'Janssen'),
(DEFAULT, 'Coordinator','John', '12345', 'John', null, 'Janssen');

INSERT INTO cursus
VALUES(DEFAULT, 'OOP', 2), 
(DEFAULT, 'OOP 2', 2), 
(DEFAULT, 'OOP 3', 2), 
(DEFAULT, 'OOP 4 ', 2), 
(DEFAULT, 'OOP 5', 2), 
(DEFAULT, 'OOP 6', 2), 
(DEFAULT, 'OOP 7', 2), 
(DEFAULT, 'OOP 6', 2), 
(DEFAULT, 'Data 1', 6), 
(DEFAULT, 'Data 2', 6), 
(DEFAULT, 'Data 3', 6), 
(DEFAULT, 'Data 4', 6), 
(DEFAULT, 'Data 5', 6), 
(DEFAULT, 'Data 6', 6), 
(DEFAULT, 'Data 7', 6), 
(DEFAULT, 'Data 8', 6);

INSERT INTO quiz
VALUES(DEFAULT, 'OOP1-1',10, 1), 
(DEFAULT, 'OOP1-2',10, 1), 
(DEFAULT, 'OOP1-3',10, 1), 
(DEFAULT, 'OOP1-4',10, 1), 
(DEFAULT, 'OOP1-5',10, 1), 
(DEFAULT, 'OOP2-1',10, 2), 
(DEFAULT, 'OOP2-2',10, 2), 
(DEFAULT, 'OOP2-3',10, 2), 
(DEFAULT, 'OOP2-4',10, 2), 
(DEFAULT, 'OOP3-1',10, 3), 
(DEFAULT, 'OOP3-2',10, 3), 
(DEFAULT, 'OOP3-3',10, 3), 
(DEFAULT, 'OOP4-1',10, 4), 
(DEFAULT, 'OOP4-2',10, 4), 
(DEFAULT, 'OOP4-3',10, 4), 
(DEFAULT, 'OOP4-4',10, 4), 
(DEFAULT, 'OOP5-1',10, 5), 
(DEFAULT, 'OOP5-2',10, 5), 
(DEFAULT, 'OOP6-1',10, 6), 
(DEFAULT, 'OOP6-2',10, 6), 
(DEFAULT, 'OOP7-1',10, 7), 
(DEFAULT, 'OOP7-2',10, 7), 
(DEFAULT, 'OOP8-1',10, 8), 
(DEFAULT, 'OOP8-2',10, 8);

INSERT INTO quiz
VALUES(DEFAULT, 'Data1',20, 9),
(DEFAULT, 'Data2',20, 10),
(DEFAULT, 'Data3',10, 11),
(DEFAULT, 'Data4',8, 12),
(DEFAULT, 'Data5',20, 13),
(DEFAULT, 'Data6',20, 14),
(DEFAULT, 'Data7',20, 15),
(DEFAULT, 'Data8',100, 16);

INSERT INTO vraag
VALUES(1,'Wat is de snelheid van het licht?', 1),
(2,'Als je een bliksemflits ziet en drie seconden later de klap hoort, hoe ver ben je dan bij de bliksemschicht vandaan?', 1),
(3,'Wat is het doppler effect?', 1),
(4,'Wat onstaat er wanneer men een base en een zuur mengt?', 1),
(5,'Wat heeft een druppel met oppervlaktespanning te maken?', 1),
(6,'Wat is de functie van een chloroplast in fotosynthese?', 2),
(7,'Wat doet het semi-permeabel membraan in osmose?', 2),
(8,'Welk element kleur bloed rood en wat is de functie van dit element in het bloed?', 2),
(9,'Wat is de functie van een enzym?', 2),
(10,'Van wat zijn de mitochondrieën een onderdeel en wat is zijn functie?' , 2);