-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 17:43:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quizmaster
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS quizmaster;
CREATE SCHEMA IF NOT EXISTS `quizmaster` DEFAULT CHARACTER SET utf8 ;
USE `quizmaster` ;

-- -----------------------------------------------------
-- Table `quizmaster`.`Gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Gebruiker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `inlognaam` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsels` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `inlognaam_UNIQUE` (`inlognaam` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `quizmaster`.`inschrijving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`inschrijving` (
  `studentid` INT NOT NULL,
  `cursusid` INT NOT NULL,
  PRIMARY KEY (`studentid`, `cursusid`),
  INDEX `fk cursus id_idx` (`cursusid` ASC) VISIBLE,
  INDEX `fk_student id_idx` (`studentid` ASC) VISIBLE,
  CONSTRAINT `volgt cursus`
    FOREIGN KEY (`studentid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `wordt gevolgd`
    FOREIGN KEY (`cursusid`)
    REFERENCES `quizmaster`.`Cursus` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `quizmaster`.`Cursus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Cursus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `coordinatorid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cursus_Gebruiker1_idx` (`coordinatorid` ASC) VISIBLE,
  CONSTRAINT `fk_Cursus_Gebruiker1`
    FOREIGN KEY (`coordinatorid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE RESTRICT
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `succesdefinitie` INT NOT NULL,
  `cursusid` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Quiz_Cursus1_idx` (`cursusid` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_Cursus1`
    FOREIGN KEY (`cursusid`)
    REFERENCES `quizmaster`.`Cursus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Vraag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Vraag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tekst` VARCHAR(240) NOT NULL,
  `quizid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vraag_Quiz1_idx` (`quizid` ASC) VISIBLE,
  CONSTRAINT `fk_Vraag_Quiz1`
    FOREIGN KEY (`quizid`)
    REFERENCES `quizmaster`.`Quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `quizmaster`.`Antwoord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Antwoord` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tekst` VARCHAR(45) NOT NULL,
  `vraagid` INT NOT NULL,
  `isjuistantwoord` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Antwoord_Vraag1_idx` (`vraagid` ASC) VISIBLE,
  CONSTRAINT `fk_Antwoord_Vraag1`
    FOREIGN KEY (`vraagid`)
    REFERENCES `quizmaster`.`Vraag` (`id`)
    ON DELETE  CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Groep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Groep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `docentid` INT NULL,
  `cursusid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Groep_Cursus1_idx` (`cursusid` ASC) VISIBLE,
  INDEX `fk_Groep_Gebruiker1_idx` (`docentid` ASC) VISIBLE,
  CONSTRAINT `fk_Groep_Cursus1`
    FOREIGN KEY (`cursusid`)
    REFERENCES `quizmaster`.`Cursus` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Groep_Gebruiker1`
    FOREIGN KEY (`docentid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Groepsindeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Groepsindeling` (
  `gebruikerid` INT NOT NULL,
  `groepid` INT NOT NULL,
  INDEX `fk_Gebruiker_has_Groep_Groep1_idx` (`groepid` ASC) VISIBLE,
  PRIMARY KEY (`gebruikerid`, `groepid`),
  CONSTRAINT `fk_Gebruiker_has_Groep_Gebruiker1`
    FOREIGN KEY (`gebruikerid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gebruiker_has_Groep_Groep1`
    FOREIGN KEY (`groepid`)
    REFERENCES `quizmaster`.`Groep` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Quizresultaat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Quizresultaat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `studentid` INT NOT NULL,
  `quizid` INT NULL,
  `quiznaam` VARCHAR(45) NOT NULL,
  `succesdefinitie` INT NOT NULL,
  `aantaljuisteantwoorden` INT NOT NULL,
  `voltooidop` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gebruiker_has_Quiz_Quiz1_idx` (`quizid` ASC) VISIBLE,
  INDEX `fk_Gebruiker_has_Quiz_Gebruiker1_idx` (`studentid` ASC) VISIBLE,
  CONSTRAINT `fk_Gebruiker_has_Quiz_Gebruiker1`
    FOREIGN KEY (`studentid`)
    REFERENCES `quizmaster`.`Gebruiker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gebruiker_has_Quiz_Quiz1`
    FOREIGN KEY (`quizid`)
    REFERENCES `quizmaster`.`Quiz` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizmaster`.`Quizvraag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizmaster`.`Quizvraag` (
  `quizid` INT NOT NULL,
  `vraagid` INT NOT NULL,
   `volgordenummer` INT NULL,
  PRIMARY KEY (`quizid`, `vraagid`),
  INDEX `fk_Quiz_has_Vraag_Vraag1_idx` (`vraagid` ASC) VISIBLE,
  INDEX `fk_Quiz_has_Vraag_Quiz1_idx` (`quizid` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_has_Vraag_Quiz1`
    FOREIGN KEY (`quizid`)
    REFERENCES `quizmaster`.`Quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Quiz_has_Vraag_Vraag1`
    FOREIGN KEY (`vraagid`)
    REFERENCES `quizmaster`.`Vraag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Gebruiker definiëren en toegang verlenen
CREATE USER IF NOT EXISTS userQuizmaster@localhost IDENTIFIED BY 'pwQuizmaster';
GRANT ALL PRIVILEGES ON quizmaster . * TO userQuizmaster@localhost;

-- INSERT

INSERT INTO gebruiker
VALUES(DEFAULT, 'Student','Hans', '12345', 'Hans', null, 'Janssen'), 
(DEFAULT, 'Coordinator','Piet', '12345', 'Piet', null, 'Janssen'),
(DEFAULT, 'Docent','Anna', '12345', 'Anna', null, 'Janssen'),
(DEFAULT, 'Administrator','Mickey', '12345', 'Mickey', null, 'Janssen'),
(DEFAULT, 'Technisch beheerder','Dorien', '12345', 'Dorien', null, 'Janssen'),
(DEFAULT, 'Coordinator','John', '12345', 'John', null, 'Janssen'),
(DEFAULT, 'Student','Wim', '12345', 'Hans', null, 'Janssen'), 
(DEFAULT, 'Student','Sjaak', '12345', 'Hans', null, 'Janssen'), 
(DEFAULT, 'Student','Lisa', '12345', 'Hans', null, 'Janssen'), 
(DEFAULT, 'Coordinator','Peter', '12345', 'Piet', null, 'Janssen'),
(DEFAULT, 'Coordinator','Mike', '12345', 'Piet', null, 'Janssen');




INSERT INTO cursus
VALUES(DEFAULT, 'OOP', 2), 
(DEFAULT, 'OOP advanced', 2), 
(DEFAULT, 'OOP extreme programming', 2), 
(DEFAULT, 'Design Patterns ', 2), 
(DEFAULT, 'Natuurkunde', 2), 
(DEFAULT, 'Wiskunde', 6), 
(DEFAULT, 'Biologie', 6), 
(DEFAULT, 'Engels', 6), 
(DEFAULT, 'Databases', 6), 
(DEFAULT, 'Data', 6);


INSERT INTO inschrijving
VALUES( 1, 1), 
( 1, 2), 
( 1, 3), 
( 7, 1), 
( 7, 2), 
( 7, 3), 
( 8, 4), 
( 8, 5), 
(8, 6), 
( 9, 4), 
( 9, 5), 
( 9, 6);


INSERT INTO groep
VALUES(DEFAULT, 'OOP gr1',2, 1),
(DEFAULT, 'Biologie g1',2, 7),
(DEFAULT, 'Wiskunde gr1',2, 6),
(DEFAULT, 'OOP g2',6, 1),
(DEFAULT, 'OOP advanced gr1',6, 2),
(DEFAULT, 'Data gr1',6, 10);




INSERT INTO groepsindeling
VALUES( 1, 1), 
( 1, 2), 
( 1, 3), 
( 7, 1), 
( 7, 2), 
( 7, 3), 
( 8, 4), 
( 8, 5), 
(8, 6), 
( 9, 4), 
( 9, 5), 
( 9, 6);



INSERT INTO quiz
VALUES(DEFAULT, 'OOP1 toets 1',10, 1), 
(DEFAULT, 'OOP toets 2',10, 1), 
(DEFAULT, 'OOP toets 3',10, 1), 
(DEFAULT, 'OOP toets 4',10, 1), 
(DEFAULT, 'OOP Examen',10, 1), 
(DEFAULT, 'advanced topics',10, 2), 
(DEFAULT, 'tools',10, 2), 
(DEFAULT, 'generic',10, 2), 
(DEFAULT, 'classes',10, 2), 
(DEFAULT, 'inheritance',10, 3), 
(DEFAULT, 'master skills',10, 3), 
(DEFAULT, 'examen extreme programming',10, 3), 
(DEFAULT, 'design patterns toets 1',10, 4), 
(DEFAULT, 'design patterns toets 2',10, 4), 
(DEFAULT, 'design patterns toets 3',10, 4), 
(DEFAULT, 'design patterns toets 4',10, 4), 
(DEFAULT, 'Krachten',10, 5), 
(DEFAULT, 'Electriciteit',10, 5), 
(DEFAULT, 'Algebra',10, 6), 
(DEFAULT, 'Meetkunde',10, 6), 
(DEFAULT, 'Planten',10, 7), 
(DEFAULT, 'het Lichaam',10, 7), 
(DEFAULT, 'Grammer',10, 8), 
(DEFAULT, 'Vocabulaire',10, 8);

INSERT INTO vraag
VALUES(DEFAULT, 'Wat is een database?',5),
(DEFAULT, 'Hoeveel regels code mag 1 stuk bevatten?',5),
(DEFAULT, 'Welke tool kan je gebruiken om samen aan software te werken?', 5),
(DEFAULT, 'Wat is geen voordeel van een NoSQL database t.o.v een SQL database?',5),
(DEFAULT, 'In wat voor vorm wordt data opgeslagen?',5),
(DEFAULT, 'Wat is geen design pattern?', 5),
(DEFAULT, 'Wat doet Maven?', 5),
(DEFAULT, 'Wat is een soort database',5),
(DEFAULT, 'Wat is big data?',5),
(DEFAULT, 'Wat zijn software requirements niet?', 5),
(DEFAULT, 'Wat is een for-loop?', 5),
(DEFAULT, 'Wat is een ArrayList', 5),
(DEFAULT, 'Hoeveel regels code mag 1 stuk bevatten volgens clean coding guid-lines?',5),
(DEFAULT, 'Juist of onjuist?', 2),
(DEFAULT, 'Wat zijn software requirements?', 1),
(DEFAULT, 'Juist, onjuist, of beide?', 4),
(DEFAULT,'Wat is de snelheid van het licht?', 1),
(DEFAULT,'Als je een bliksemflits ziet en drie seconden later de klap hoort, hoe ver ben je dan bij de bliksemschicht vandaan?', 1),
(DEFAULT,'Wat is het doppler effect?', 1),
(DEFAULT,'Wat onstaat er wanneer men een base en een zuur mengt?', 1),
(DEFAULT,'Wat heeft een druppel met oppervlaktespanning te maken?', 1),
(DEFAULT,'Wat is de functie van een chloroplast in fotosynthese?', 2),
(DEFAULT,'Wat doet het semi-permeabel membraan in osmose?', 2),
(DEFAULT,'Welk element kleur bloed rood en wat is de functie van dit element in het bloed?', 2),
(DEFAULT,'Wat is de functie van een enzym?', 2),
(DEFAULT,'Van wat zijn de mitochondrieën een onderdeel en wat is zijn functie?' , 2);

INSERT INTO quizvraag
VALUES( 5, 1, 1), 
( 5, 2, 2), 
( 5, 3, 3), 
( 5, 4, 4), 
( 5, 5, 5), 
( 5, 6, 6), 
( 5, 7, 7), 
( 5, 8, 8), 
( 5, 9, 9), 
( 5, 10, 10), 
( 5, 11, 11), 
( 5, 12, 12), 
( 5, 13, 13);

INSERT INTO antwoord
VALUES( DEFAULT, 'Een gestructureerde set van opgeslagen data', 1, true), 
( DEFAULT, 'Een harde schijf', 1, false), 
( DEFAULT, 'Een basis van data', 1, false), 
( DEFAULT, 'Een plek op data op te slaan', 1, false), 
( DEFAULT, 'zoveel als nodig is', 2, false), 
( DEFAULT, 'indien mogelijk niet meer dan 15', 2, true), 
( DEFAULT, 'Indien mogelijk niet meer dan 20',2, false), 
( DEFAULT, 'Indien mogelijk niet meer dan 12', 2, false), 
( DEFAULT, 'Maven', 3, false), 
( DEFAULT, 'Git', 3, true), 
( DEFAULT, 'Word', 4, false), 
( DEFAULT, 'IntelliJ', 4, false),
( DEFAULT, 'Een harde schijf', 5, false), 
( DEFAULT, 'Een basis van data',5, false), 
( DEFAULT, 'Een plek op data op te slaan', 6, false), 
( DEFAULT, 'zoveel als nodig is', 6, false), 
( DEFAULT, 'indien mogelijk niet meer dan 15', 6, true), 
( DEFAULT, 'Indien mogelijk niet meer dan 20', 7, false), 
( DEFAULT, 'Indien mogelijk niet meer dan 12', 7, false), 
( DEFAULT, 'Maven',7, false), 
( DEFAULT, 'Git', 8, true), 
( DEFAULT, 'Word',8, false), 
( DEFAULT, 'IntelliJ', 8, false),
( DEFAULT, 'Een basis van data',9, false), 
( DEFAULT, 'Een plek op data op te slaan',9, false), 
( DEFAULT, 'zoveel als nodig is', 11, false), 
( DEFAULT, 'indien mogelijk niet meer dan 15', 11, true), 
( DEFAULT, 'Indien mogelijk niet meer dan 20', 11, false), 
( DEFAULT, 'Indien mogelijk niet meer dan 12', 12, false), 
( DEFAULT, 'Maven',12, false), 
( DEFAULT, 'Git', 12, true), 
( DEFAULT, 'Word',12, false), 
( DEFAULT, 'IntelliJ', 13, false),
( DEFAULT, 'Word',13, false), 
( DEFAULT, 'IntelliJ', 13, false);


